### ISSUE TITLE
trouble installing.

### ISSUE THREAD

**Issue by twonk** [nebrius/raspi-gpio#1]
Hi Bryan, I've been trying to install raspi-io along with johnny-five.  When I run

```
sudo npm install -g raspi-io 
```

it works away for a while and then fails at the raspi-gpio installation step.   Running 

```
sudo npm install -g raspi-gpio 
```

also fails.
Here's the terminal output.   Can you offer any advice?  This is on a fresh installation of raspbian, along with node version 0.10.28

```
# npm install -g raspi-gpio
npm http GET https://registry.npmjs.org/raspi-gpio
npm http 304 https://registry.npmjs.org/raspi-gpio
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/raspi-peripheral
npm http 304 https://registry.npmjs.org/raspi-peripheral
npm http 304 https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/raspi-board
npm http 304 https://registry.npmjs.org/raspi-board

> raspi-gpio@1.0.3 install /usr/local/lib/node_modules/raspi-gpio
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.28"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/raspi-gpio/.node-gyp"
gyp http GET http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.28/node-v0.10.28.tar.gz
gyp http GET http://nodejs.org/dist/v0.10.28/SHASUMS.txt
gyp http 200 http://nodejs.org/dist/v0.10.28/SHASUMS.txt
make: Entering directory '/usr/local/lib/node_modules/raspi-gpio/build'
  CXX(target) Release/obj.target/addon/src/addon.o
../src/addon.cc: In function ‘void InitAll(v8::Handle<v8::Object>)’:
../src/addon.cc:40:35: error: no matching function for call to ‘NanNew(<unresolved overloaded function type>)’
../src/addon.cc:40:35: note: candidates are:
../node_modules/nan/nan_implementation_pre_12_inl.h:210:1: note: template<class T> v8::Local<T> NanNew(v8::Handle<T>)
../node_modules/nan/nan_implementation_pre_12_inl.h:216:1: note: template<class T> v8::Local<T> NanNew(const v8::Persistent<S>&)
../node_modules/nan/nan_new.h:177:1: note: template<class T> typename NanIntern::Factory::return_t NanNew()
../node_modules/nan/nan_new.h:183:1: note: template<class T, class A0> typename NanIntern::Factory<T>::return_t NanNew(A0)
../node_modules/nan/nan_new.h:189:1: note: template<class T, class A0, class A1> typename NanIntern::Factory<T>::return_t NanNew(A0, A1)
../node_modules/nan/nan_new.h:195:1: note: template<class T, class A0, class A1, class A2> typename NanIntern::Factory<T>::return_t NanNew(A0, A1, A2)
../node_modules/nan/nan_new.h:201:1: note: template<class T, class A0, class A1, class A2, class A3> typename NanIntern::Factory<T>::return_t NanNew(A0, A1, A2, A3)
../src/addon.cc:42:34: error: no matching function for call to ‘NanNew(<unresolved overloaded function type>)’
../src/addon.cc:42:34: note: candidates are:
../node_modules/nan/nan_implementation_pre_12_inl.h:210:1: note: template<class T> v8::Local<T> NanNew(v8::Handle<T>)
../node_modules/nan/nan_implementation_pre_12_inl.h:216:1: note: template<class T> v8::Local<T> NanNew(const v8::Persistent<S>&)
../node_modules/nan/nan_new.h:177:1: note: template<class T> typename NanIntern::Factory::return_t NanNew()
../node_modules/nan/nan_new.h:183:1: note: template<class T, class A0> typename NanIntern::Factory<T>::return_t NanNew(A0)
../node_modules/nan/nan_new.h:189:1: note: template<class T, class A0, class A1> typename NanIntern::Factory<T>::return_t NanNew(A0, A1)
../node_modules/nan/nan_new.h:195:1: note: template<class T, class A0, class A1, class A2> typename NanIntern::Factory<T>::return_t NanNew(A0, A1, A2)
../node_modules/nan/nan_new.h:201:1: note: template<class T, class A0, class A1, class A2, class A3> typename NanIntern::Factory<T>::return_t NanNew(A0, A1, A2, A3)
addon.target.mk:85: recipe for target 'Release/obj.target/addon/src/addon.o' failed
make: *** [Release/obj.target/addon/src/addon.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/raspi-gpio/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Linux 3.12.35+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/raspi-gpio
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm ERR! raspi-gpio@1.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the raspi-gpio@1.0.3 install script.
npm ERR! This is most likely a problem with the raspi-gpio package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls raspi-gpio
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.12.35+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "raspi-gpio"
npm ERR! cwd /
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /npm-debug.log
npm ERR! not ok code 0
```

Many thanks, Andy

**Comment by nebrius** [comment]
Hi Andy,

Have you installed [raspi-core](https://github.com/bryan-m-hughes/raspi-core)? This is a necessary prerequisite for raspi-gpio, and is _probably_ why you got the compile error. I added a blurb to the README to hopefully make this more obvious.

Also, you will need to install it with `npm install raspi-gpio` (no -g flag). Raspi-gpio does not have a command associated with it, it is a library only. With NPM, only commands can be installed globally, libraries can't. If you do `require('raspi-gpio')` with it installed globally, you will get `Error: Cannot find module 'raspi-gpio'`.

**Comment by twonk** [comment]
Hi Bryan, thanks for getting back to me. I've done some more digging. I have all of the pre-requisites. The problem seems to be with the version of Nan that's required. The packages.json has the nan dependency on version ^1.4.0 so it takes version 1.5.0  (ands fails to compile). If I clone the repo and set the dependency to =1.4.1 and compile myself it works ok!

Cheers,
Andy

**Comment by nebrius** [comment]
_smacks forhead_. Right, I forgot a new version was released that supports io.js. Thanks for digging! I published a new version of this module (and the others that depend on NAN) that locks it to 1.4.x for the time being.

**Comment by twonk** [comment]
Perfect! Thanks - installs without issue through npm now :+1:
